#version 460
layout(local_size_x = 20, local_size_y = 20) in;
layout(rgba8, binding = 0) uniform writeonly image2D destText;


void main()
{
  vec4 pixel = vec4(1.0f, 0.7f, 1.0f, 1.0f);
  // get index in global work group i.e x,y position
  ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
  
  //
  // interesting stuff happens here later
  //
  
  // output to a specific pixel in the image
  imageStore(destText, pixel_coords, pixel);
}